set next

GREETING="Hello"

# Build the project
build:
    cargo build --release

# Run tests
test:
    cargo test

# Test variable persistence
test-vars:
    FOO=$(echo "bar")
    echo "FOO is: $FOO"
    export BAZ="qux"
    echo "BAZ is: $BAZ"

# Test arguments
greet NAME:
    echo "$GREETING, $NAME!"

# Test variadic args
echo-all *ARGS:
    echo "Args: $@"
    echo "Quoted: $1 $2"

# Test shift
test-shift NAME *ARGS:
    echo "Before shift: $@"
    shift
    echo "After shift: $@"

# Default parameter
deploy ENV=staging:
    echo "Deploying to $ENV"
